services:
  - type: web
    name: flask-todo
    env: python
    plan: starter    # ปรับตามงบ
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo-postgres
          property: connectionString

databases:
  - name: todo-postgres
    plan: starter